/**
 * Rust code generator
 */

import * as fs from 'fs'
import { range, snakeCase } from 'lodash'
import { normalizeTypes } from '../utils'
import { TypeDefinition, TypeDefinitionStrict, Field } from '../'
import { Kind, EnumStrict, UnionStrict } from '../types'

type TypeMapping = { [k: string]: (size: number) => string }

type Options = {
  typeMapping?: TypeMapping
  attribute?: string
}

export const defaultOptions = {
  attribute: '',
}

export const defaultMapping: TypeMapping = {
  'char[]': size => `[u8; ${size}]`,
}

const indent = (i: number) => (str: string) => {
  return '                    '.substr(-i) + str
}

const getMembers = (fields: Field[], typeMap: TypeMapping) => {
  return fields.map(field => {
    const key = field.type + (field.length ? '[]' : '')
    const rustType = field.length ? `[${field.type}; ${field.length}]` : field.type
    const theType = (typeMap[key] !== undefined)
      ? typeMap[key](field.length)
      : rustType

    return `  pub ${field.name}: ${theType},`
  })
}

const getEnum = (
  { name, variants }: EnumStrict,
  attribute: string
) => {
  const variantsFields = variants.map(([key, value]) => `  ${key} = ${value},`).join('\n')
  return `${attribute}
pub enum ${name} {
${variantsFields}
}`
}

const getUnion = (
  { name, members }: UnionStrict,
  attribute: string
) => {
  
  const unionMembers = members.map(member => {
    return `  ${snakeCase(member)}: ${member},`
  }).join('\n')

  return `${attribute}
pub union ${name} {
${unionMembers}
}`
}

/**
 * Generate TypeScript interfaces from Bendec types definitions
 */
export const generateString = (
  typesDuck: TypeDefinition[],
  options: Options = defaultOptions
) => {

  const ignoredTypes = ['char']

  const types: TypeDefinitionStrict[] = normalizeTypes(typesDuck)
  const { typeMapping } = { ...defaultOptions, ...options }
  const typeMap: TypeMapping = { ...defaultMapping, ...typeMapping }

  const definitions = types.map(typeDef => {
    const typeName = typeDef.name

    if (typeMap[typeName]) {
      return `pub type ${typeName} = ${typeMap[typeName]}`
    }

    if (ignoredTypes.includes(typeName)) {
      return `// ignored: ${typeName}`
    }

    if (typeDef.kind === Kind.Primitive) {
      return `// primitive build-in: ${typeName}`
    }

    if (typeDef.kind === Kind.Alias) {
      return `pub type ${typeName} = ${typeDef.alias};`
    }

    if (typeDef.kind === Kind.Union) {
      return getUnion(typeDef, options.attribute)
    }

    if (typeDef.kind === Kind.Enum) {
      return getEnum(typeDef, options.attribute)
    }

    if (typeDef.kind === Kind.Struct) {
      const members = typeDef.fields
        ? getMembers(typeDef.fields, typeMap)
        : []

      const membersString = members.join('\n')

      return `${options.attribute}
#[repr(C, packed)]
pub struct ${typeName} {
${membersString}
}`
    }
  })

  const result = definitions.join('\n\n')
    return `/** GENERATED BY BENDEC TYPE GENERATOR */
  ${result}
`
}

/**
 * Generate Rust types from Bendec types definitions
 */
export const generate = (types: any[], fileName: string, options?: Options) => {
  const moduleWrapped = generateString(types, options)

  fs.writeFileSync(fileName, moduleWrapped)
  console.log(`WRITTEN: ${fileName}`)
}
