/**
 * Rust code generator
 */
import * as fs from 'fs'
import { range, snakeCase, get, keyBy, flatten } from 'lodash'
import { normalizeTypes } from '../utils'
import { TypeDefinition, TypeDefinitionStrict, Field } from '../'
import {
  Lookup, Kind, StructStrict, AliasStrict, EnumStrict, UnionStrict
} from '../types'
export * from './rust/types'

import {
  TypeName, TypeMapping, NewtypeKind, NewtypePublic, NewtypePrivate,
  NewtypeInCrate, NewtypeDef, TypeMeta, Options,
  FieldName, FieldMeta
} from './rust/types'
import { getUnion } from './rust/gen/union'
import { getEnum } from './rust/gen/enum'
import { getStruct } from './rust/gen/struct'
import { getAlias } from './rust/gen/alias'
import { hexPad, indent, smoosh } from './utils'
import { doc, createDerives, toRustNS } from './rust/utils'

let globalBigArraySizes = []

export const defaultOptions = {
  lookupTypes: [[]],
  extras: [],
  extraDerives: {},
  meta: {},
  camelCase: false,
  enumConversionError: {
    type: '{{ underlying }}',
    constructor: 'other'
  },
  forEachType: ([generated, context]) => generated
}

export const defaultMapping: TypeMapping = {
  'char[]': size => `[u8; ${size}]`,
}

const pushBigArray = (length: number): string => {
  if (globalBigArraySizes.indexOf(length) == -1) {
    globalBigArraySizes.push(length)
  }
  return '  #[serde(with = "BigArray")]\n'
}

/**
 * Generate Rust types from Bendec types definitions
 */
export const generateString = (
  typesDuck: TypeDefinition[],
  options: Options = defaultOptions
) => {

  globalBigArraySizes = []
  const ignoredTypes = ['char']

  const types: TypeDefinitionStrict[] = normalizeTypes(typesDuck)
  const lookupTypes = normalizeTypes(flatten(options.lookupTypes))
  const lookup = keyBy(types.concat(lookupTypes), i => i.name)

  options = { ...defaultOptions, ...options }

  const { typeMapping, extraDerives = [], meta } = options 
  const typeMap: TypeMapping = { ...defaultMapping, ...typeMapping }

  const definitions = types.map(typeDef => {
    // This is what we pass into callback function for each type def
    const context = typeDef

    const typeName = typeDef.name

    const extraDerivesArray = get(extraDerives, typeName, [])

    if (typeMap[typeName]) {
      return [`pub type ${typeName} = ${typeMap[typeName]()};`, context]
    }

    if (ignoredTypes.includes(typeName)) {
      return [`// ignored: ${typeName}`, context]
    }

    if (typeDef.kind === Kind.Primitive) {
      return [`// primitive built-in: ${typeName}`, context]
    }

    if (typeDef.kind === Kind.Alias) {
      return [
        getAlias(typeName, typeDef.alias, meta, extraDerivesArray, typeDef.description),
        context
      ]
    }

    if (typeDef.kind === Kind.Union) {
      return [getUnion(typeDef, types), context]
    }

    if (typeDef.kind === Kind.Enum) {
      return [getEnum(typeDef, options.enumConversionError, meta, extraDerivesArray), context]
    }

    if (typeDef.kind === Kind.Struct) {
      return [
        getStruct(typeDef, lookup, typeMap, meta, extraDerivesArray, options.camelCase),
        context
      ]
    }

    if (typeDef.kind === Kind.Array) {
      const { name, type, length } = typeDef
      const alias = `[${toRustNS(typeDef.type)}; ${typeDef.length}]`
      return [
        getAlias(typeName, alias, meta, extraDerivesArray, typeDef.description),
        context
      ]
    }
  })

  const result = definitions.map(options.forEachType).join('\n\n')
  const extrasString = options.extras.join('\n')
  const bigArraySizesString = globalBigArraySizes.length > 0
    ? `big_array! { BigArray; ${globalBigArraySizes.join(',')}, }`
    : ''

  return smoosh([
`/** GENERATED BY BENDEC TYPE GENERATOR */
#[allow(unused_imports)]
use serde::{Deserialize, Deserializer, Serialize, Serializer};`,
bigArraySizesString,
extrasString,
result])
}

/**
 * Generate Rust types from Bendec types definitions
 */
export const generate = (types: TypeDefinition[], fileName: string, options?: Options) => {
  const moduleWrapped = generateString(types, options)

  fs.writeFileSync(fileName, moduleWrapped)
  console.log(`WRITTEN: ${fileName}`)
}
